#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bscp config left_padding	30

#AutoStart applications
sxhkd &
picom -b&
nitrogen --restore &
dunst &
polybar -q main &
